# Generated by Django 3.0.5 on 2023-12-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_donor_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='address',
            new_name='department',
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.CharField(default=123, max_length=40),
            preserve_default=False,
        ),
    ]
