# Generated by Django 3.0.5 on 2023-12-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default=123, max_length=40),
            preserve_default=False,
        ),
    ]
